FROM ubuntu

ENV RAILS_ENV={{ RAILS_ENV }}
ENV SECRET_KEY_BASE={{ SECRET_KEY_BASE }}
ENV REDMINE_LANG=en

RUN apt-get update && apt-get upgrade -y &&  \
    apt install -y apache2 ruby ruby-dev build-essential libapache2-mod-passenger libmysqlclient-dev mysql-client

RUN . /etc/apache2/envvars

WORKDIR /opt

COPY ./{{ REDMINE_VERSION }} ./{{ REDMINE_VERSION }}

RUN ln -s {{ REDMINE_VERSION }} redmine

WORKDIR /opt/redmine

COPY ./database.yml ./config/database.yml

COPY ./redmine.conf /etc/apache2/sites-available

RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf 

RUN echo "gem 'tzinfo-data'">>Gemfile &&\
    gem install bundler && bundle install  

RUN a2dissite 000-default.conf && a2ensite redmine.conf

EXPOSE 80

RUN apachectl stop

COPY ./start.sh .

CMD ["./start.sh"]