---
# tasks file for redmine-in-docker

- name: Install prerequisites
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
   - ca-certificates 
   - curl
   - gnupg  

- name: Make sure /etc/apt/keyrings exists
  file:
    path: /etc/apt/keyrings
    recurse: yes
    state: directory 

- name: Remove docker.gpg
  file:
    path: /etc/apt/keyrings/docker.gpg
    state: absent


- name: Add Docker's official GPG key
  shell:
    cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg 

- name: Add Docker list
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    line: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"         
    state: present
    create: yes

- name: Install Pip and Docker
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - python3-pip
    - docker-ce 
    - docker-ce-cli
    - containerd.io 
    - docker-compose-plugin

- name: Install Docker Modules for Python
  pip:
    name: "{{item}}"
  loop:
    - docker
    - docker-compose

- name: Make sure destination dir exists
  file:
    path: "{{ REDMINE_DIR }}"
    state: directory

- name: Download and unarchive Redmine
  ansible.builtin.unarchive:
    src: "https://redmine.org/releases/{{ REDMINE_VERSION }}.tar.gz"
    dest: "{{ REDMINE_DIR }}"
    remote_src: yes

- name: Render Dockerfile template
  template:
    src: Dockerfile.j2
    dest: "{{ REDMINE_DIR }}/Dockerfile"

- name: Render docker-compose template
  template:
    src: docker-compose.yml.j2
    dest: "{{ REDMINE_DIR }}/docker-compose.yml"

- name: Render database for redmine template
  template:
    src: database.yml.j2
    dest: "{{ REDMINE_DIR }}/database.yml"

- name: Copy Apache config
  copy:
    src: ./files/apache/redmine.conf
    dest: "{{ REDMINE_DIR }}/redmine.conf"

- name: Copy startup script
  copy:
    src: ./files/start.sh
    dest: "{{ REDMINE_DIR }}" 
    mode: "0755"   

- name: Build image of redmine container
  community.docker.docker_image:
    name: redmine-in-docker
    build:
      path: "{{ REDMINE_DIR }}"
    source: build

- name: Deploy Docker Compose stack
  community.docker.docker_compose:
    project_src: "{{ REDMINE_DIR }}"
    files: docker-compose.yml
